# config.yaml
modules:
  affair:
    prefix: 校務專區
  bus:
    prefix: 公車
  dining:
    prefix: 學生餐廳
  help:
    prefix: 說明
  info:
    prefix: 公佈欄
  library:
    prefix: 圖書館
  magic:
    prefix: 神奇海螺
  map:
    prefix: 地圖
  menu:
    prefix: 選單
