apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: gcr.io/predictive-goal-263306/nthu-chatbot-client:latest
        imagePullPolicy: Always
        name: nthu-chatbot-client
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Asia/Taipei